app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
Route::resource('admin','BebidasController');
Route::resource('proveedores','ProveedoresController');
Route::get('proveedores/{proveedores}/destroy',[
  'uses'=>'ProveedoresController@destroy',
  'as' => 'proveedores.destroy'
]);
Route::resource('bebidas','BebidasController');
Route::get('bebidas/{bebidas}/destroy',[
  'uses'=>'BebidasController@destroy',
  'as' => 'bebidas.destroy'
]);
Route::resource('extras','ProductosExtraController');
Route::get('extras/{extras}/destroy',[
  'uses'=>'ProductosExtraController@destroy',
  'as' => 'extras.destroy'
]);
Route::resource('tipos','TiposBebidaController');
Route::get('tipos/{tipos}/destroy',[
  'uses'=>'TiposBebidaController@destroy',
  'as' => 'tipos.destroy'
]);
Route::resource('combos','CombosController');
Route::get('combos/{combos}/destroy',[
  'uses'=>'CombosController@destroy',
  'as' => 'combos.destroy'
]);
Route::resource('categorias','CategoriasController');
Route::get('categorias/{categorias}/destroy',[
  'uses'=>'CategoriasController@destroy',
  'as' => 'categorias.destroy'
]);
Route::resource('cigarros','CigarrosController');
Route::get('cigarros/{cigarros}/destroy',[
  'uses'=>'CigarrosController@destroy',
  'as' => 'cigarros.destroy'
]);
Route::resource('combo-bebidas','ComboBebidasController');

Route::resource('combo-extras','ComboExtrasController');

Route::get('bebidas/icons',[
  'uses'=>'BebidasController@icons',
  'as' => 'bebidas.icons'
]);

app/Http/Controllers/TiposBebidaController.php
<?php

namespace AgenciaAdmin\Http\Controllers;

use Illuminate\Http\Request;
use AgenciaAdmin\TipoBebida;
use AgenciaAdmin\Http\Requests;
use Session;
class TiposBebidaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $tipos = TipoBebida::getAll();
        return view('tiposbebida.index',compact('tipos'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('tiposbebida.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        TipoBebida::create($request->all());
        Session::flash('store-success','Datos registrados correctamente !');
        return redirect()->route('tipos.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $tipo = TipoBebida::find($id);
        return view('tiposbebida.edit',['tipo'=>$tipo]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $tipo = TipoBebida::find($id);
        $tipo->tipo = $request->tipo;
        $tipo->observaciones = $request->observaciones;
        $tipo->save();
        Session::flash('update-success','Datos actualizados correctamente !');
        return redirect()->route('tipos.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $tipo = TipoBebida::find($id);
        $tipo->delete();
        Session::flash('delete-success','Datos eliminados correctamente !');
        return redirect()->route('tipos.index');
    }
}

resources/views/tiposbebida/create.blade.php
@extends('agencia.principal')
@section('content')
<div class="row">
	<div class="col-lg-12">
		<div class="widget-container fluid-height clearfix">
			<div class="heading">
				<i class="fa fa-bars"></i>Registrar nuevo tipo de bebida
			</div>
			<div class="widget-content padded">
				{!! Form::open(['route'=>'tipos.store','method'=>'POST','class'=>'form-horizontal']) !!}
				@include('tiposbebida.form.form')
				<div class="form-group">
					<div class="col-md-7" >
						{!!Form::submit('Registrar',['class'=>'btn btn-primary'])!!} <a class="btn btn-default-outline" href="{!! URL::to('tipos') !!}">Cancelar</a>
					</div>
				</div>
				{!! Form::close() !!}
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/tiposbebida/edit.blade.php
@extends('agencia.principal')
@section('content')
<div class="row">
	<div class="col-lg-12">
		<div class="widget-container fluid-height clearfix">
			<div class="heading">
				<i class="fa fa-bars"></i>Actualizar datos del tipo de bebida
			</div>
			<div class="widget-content padded">
				{!!Form::model($tipo,['route'=>['tipos.update',$tipo->id],'method'=>'PUT','class'=>'form-horizontal'])!!}
				@include('tiposbebida.form.form')
				<div class="form-group">
					<div class="col-md-7" >
						{!!Form::submit('Actualizar',['class'=>'btn btn-primary'])!!} <a class="btn btn-default-outline" href="{!! URL::to('tipos') !!}">Cancelar</a>
					</div>
				</div>
				{!! Form::close() !!}
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/tiposbebida/index.blade.php
@extends('agencia.principal')
@section('content')
<div class="row">
  <div class="col-lg-12">
    <div class="widget-container fluid-height clearfix">
      <div class="heading">
        <i class="fa fa-table"></i>Todos los tipos de bebida
        <a class="btn btn-primary pull-right" data-style="expand-right" href="{!! URL::to('tipos/create') !!}"><i class="fa fa-plus"></i>Agregar nuevo</a>
        &nbsp;<a class="btn btn-info pull-right" data-style="expand-right" href="{!! URL::to('tipos') !!}"><i class="fa fa-refresh"></i>Actualizar</a>
      </div>
      <div class="widget-content padded clearfix">
        <div id="dataTable1_wrapper" class="dataTables_wrapper" role="grid">
          <div class="dataTables_filter" id="dataTable1_filter">
            <label>Buscar:
              <input type="text" aria-controls="dataTable1">
            </label>         
          </div>
          <table class="table table-bordered table-striped dataTable" aria-describedby="dataTable1_info">
            <thead>
              <tr role="row">
                <th class="sorting_asc" role="columnheader" tabindex="0" rowspan="1" colspan="1"  style="width: 183px;">
                  Tipo de bebida
                </th>
                <th class="sorting_asc" role="columnheader" tabindex="0" aria-controls="dataTable1" rowspan="1" colspan="1" style="width: 183px;">
                  Observaciones
                </th>
                <th class="sorting_asc" role="columnheader" tabindex="0" aria-controls="dataTable1" rowspan="1" colspan="1" style="width: 183px;">
                  Fecha de creaci&oacute;n
                </th>
                <th class="sorting_asc" role="columnheader" tabindex="0" aria-controls="dataTable1" rowspan="1" colspan="1" style="width: 183px;">
                  Fecha de modificaci&oacute;n
                </th>
                <th class="sorting_asc" role="columnheader" tabindex="0" aria-controls="dataTable1" rowspan="1" colspan="1" style="width: 50px;">
                  Acci&oacute;n
                </th>
              </tr>
            </thead>
            <tbody role="alert" aria-live="polite" aria-relevant="all">
              @foreach($tipos as $tipo)
              <tr class="odd">
                <td class=" sorting_1">
                  {{ $tipo->tipo }}
                </td>
                <td class="">
                  {{ $tipo->observaciones }}
                </td>
                <td class="hidden-xs">
                  {{ $tipo->created_at }}
                </td>
                <td class="hidden-xs">
                  {{ $tipo->updated_at }}
                </td>
                <td class="actions ">
                  <div class="action-buttons" align="center">
                    <a class="table-actions" data-toggle="modal" href="#myModal{{ $tipo->id }}"><i class="fa fa-eye"></i></a>
                    <a class="table-actions" href="{!! route('tipos.edit',$parameters = $tipo->id) !!}">
                      <i class="fa fa-pencil"></i>
                    </a>
                    <a class="table-actions" href="{!! route('tipos.destroy',$parameters = $tipo->id) !!}">
                      <i class="fa fa-trash-o"></i>
                    </a>
                  </div>
                  <div class="modal fade" id="myModal{{ $tipo->id }}" aria-hidden="true" style="display: none;">
                  <div class="modal-dialog">
                    <div class="modal-content">
                      <div class="modal-header">
                        <button aria-hidden="true" class="close" data-dismiss="modal" type="button">×</button>
                        <h4 class="modal-title">
                          Detalles
                        </h4>
                      </div>
                      <div class="modal-body">
                        <h1>
                          Detalles del producto
                        </h1>
                        <p><b>Tipo de bebida: </b></p>
                        <p>{{ $tipo->tipo }}</p>
                        <p><b>Observaciones: </b></p>
                        <p>{{ $tipo->observaciones }}</p>
                        <p><b>Fecha de creaci&oacute;n</b></p>
                        <p>{{ $tipo->created_at }}</p>
                        <p><b>Fecha de modificaci&oacute;n: </b></p>
                        <p>{{ $tipo->updated_at }}</p>
                      </div>
                      <div class="modal-footer">
                        <button class="btn btn-default-outline" data-dismiss="modal" type="button">Cerrar</button>
                      </div>
                    </div>
                  </div>
                </div>
                </td>
              </tr>
              @endforeach
            </tbody>
          </table>
          {{ $tipos->render() }}
          @include('alerts.success')
        </div>
      </div>
    </div>
  </div>
  @endsection